### ISSUE TITLE
NativeVotes not working on TF2C

### ISSUE THREAD

**Issue by RoonMoonlight** [sapphonie/sourcemod-nativevotes-updated#33] opened 2023-01-19 08:50 UTC
On [Team Fortress 2 Classic](https://tf2classic.com), if mapchooser extended tries to call NativeVotes, the below error displays.

![TF2C Broken](https://user-images.githubusercontent.com/25527589/213396868-92e7cc21-6be6-499d-b7e2-4c6516d32ae9.png)

**Comment by sapphonie** [comment] 2023-01-19 09:15
Caused by an update to tf2 breaking nativevotes as seen in #16, PRs are welcome

**Comment by RoonMoonlight** [comment] 2023-01-19 09:24
> Caused by an update to tf2 breaking nativevotes as seen in #16, PRs are welcome

I mean the Team Fortress 2 Classic mod, not Team Fortress 2

**Comment by sapphonie** [comment] 2023-01-19 09:47
> > Caused by an update to tf2 breaking nativevotes as seen in #16, PRs are welcome
> 
> I mean the Team Fortress 2 Classic mod, not Team Fortress 2
> 
> or is it related?

Yes, I am aware, I develop for TF2C. This issue is due to TF2Classic not having the same structure that TF2 has for votes; I am too busy to be able to do this myself, though it should be trivial by simply adding a check for TF2C and using the old behavior instead of modern TF2 behavior

**Comment by LifeDreamer24** [comment] 2023-05-05 22:42
Will this be fixed soon? I'm also trying to add it to my server :o

**Comment by RoonMoonlight** [comment] 2023-05-06 02:22
> Will this be fixed soon? I'm also trying to add it to my server :o

Hope it should be fixed soon, you can make pull request if you can't wait and you have knowledge about SourcePawn

**Comment by LifeDreamer24** [comment] 2023-05-06 05:24
Wish i had/could... 😕
How about you? Are you enough experienced with sourcepawn and would be willing to spend time on fixing it?
Otherwise i just won't add it to my server i guess 😆

**Comment by RoonMoonlight** [comment] 2023-05-06 05:25
> Wish i had/could... 😕 How about you? Are you enough experienced with sourcepawn and would be willing to spend time on fixing it? Otherwise i just won't add it to my server i guess 😆

Of course not as well, I have lack of knolwedges about SourcePawn (But I ported some of plugins into TF2C successfully)

**Comment by LifeDreamer24** [comment] 2023-05-06 05:36
Oh okay no worries 👌
It's nice to know that you succeed on porting plugins however 😄
I'm currently searching for additional plugins to add on my server, do you have any public works you wouldn't mind sharing with me?

**Comment by sapphonie** [comment] 2023-05-06 17:06
> Will this be fixed soon? I'm also trying to add it to my server :o

PRs are welcome. I have a full time job, I'm probably not going to have to time to look at this for a while

**Comment by LifeDreamer24** [comment] 2023-05-08 03:53
https://github.com/sapphonie/sourcemod-nativevotes-updated/releases/tag/workflow-build10
Works in tf2c

**Comment by RoonMoonlight** [comment] 2023-05-08 03:54
> https://github.com/sapphonie/sourcemod-nativevotes-updated/releases/tag/workflow-build10 Works in tf2c

Thank you! Will be testing on my server soon.

**Comment by LifeDreamer24** [comment] 2023-05-08 04:14
Many thanks to a kind person on their official discord server to help me find a solution on making the panel work like their official servers :)

**Comment by sapphonie** [comment] 2023-05-09 06:45
Resolved in #34, see https://github.com/sapphonie/sourcemod-nativevotes-updated/releases/latest

**Closed by sapphonie** 2023-05-09 06:45 UTC
